version: "3"
services:
  frontend:
    build:
      context: ./jick_front/
      dockerfile: Dockerfile
    ports:
      - 5173:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./jick_backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8080
